# Host to use for canonical URL generation (without trailing slash)
host: https://govuk-k8s-user-docs.publishing.service.gov.uk

# Header-related options
show_govuk_logo: true
service_name: GOV.UK Kubernetes Cluster User Docs
service_link: https://govuk-k8s-user-docs.publishing.service.gov.uk
phase: Alpha

# Links to show on right-hand-side of header
header_links:
  Documentation: /
  # About: https://www.larry-the-cat.service.gov.uk/about
  # Get Started: https://www.larry-the-cat.service.gov.uk/get-started
  # Support: https://www.larry-the-cat.service.gov.uk/support

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: false

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: false

# Enable collapsible navigation in the sidebar
collapsible_nav: false

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: alphagov/govuk-kubernetes-cluster-user-docs
github_branch: main
owner_slack_workspace: gds
default_owner_slack: '#govuk-replatforming'
